name: Azure Credentials CI

on:
  push:
    branches:
      - main

jobs:
  azuread:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        shell: pwsh
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}